server:
  port: 8888

spring:
  application:
    name: 03-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Krzysztof/Documents/InteliiJProjects/learning/in28minutes/microservices/git-localconfig-repo